// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: protobuf/proto/broadcast.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BroadcastService_BroadcastPlayerNotify_FullMethodName = "/BroadcastService/BroadcastPlayerNotify"
)

// BroadcastServiceClient is the client API for BroadcastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BroadcastServiceClient interface {
	// 服务端向客户端主动发送消息
	BroadcastPlayerNotify(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (BroadcastService_BroadcastPlayerNotifyClient, error)
}

type broadcastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastServiceClient(cc grpc.ClientConnInterface) BroadcastServiceClient {
	return &broadcastServiceClient{cc}
}

func (c *broadcastServiceClient) BroadcastPlayerNotify(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (BroadcastService_BroadcastPlayerNotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &BroadcastService_ServiceDesc.Streams[0], BroadcastService_BroadcastPlayerNotify_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastServiceBroadcastPlayerNotifyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BroadcastService_BroadcastPlayerNotifyClient interface {
	Recv() (*PlayerBroadcast, error)
	grpc.ClientStream
}

type broadcastServiceBroadcastPlayerNotifyClient struct {
	grpc.ClientStream
}

func (x *broadcastServiceBroadcastPlayerNotifyClient) Recv() (*PlayerBroadcast, error) {
	m := new(PlayerBroadcast)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcastServiceServer is the server API for BroadcastService service.
// All implementations must embed UnimplementedBroadcastServiceServer
// for forward compatibility
type BroadcastServiceServer interface {
	// 服务端向客户端主动发送消息
	BroadcastPlayerNotify(*BroadcastRequest, BroadcastService_BroadcastPlayerNotifyServer) error
	mustEmbedUnimplementedBroadcastServiceServer()
}

// UnimplementedBroadcastServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBroadcastServiceServer struct {
}

func (UnimplementedBroadcastServiceServer) BroadcastPlayerNotify(*BroadcastRequest, BroadcastService_BroadcastPlayerNotifyServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastPlayerNotify not implemented")
}
func (UnimplementedBroadcastServiceServer) mustEmbedUnimplementedBroadcastServiceServer() {}

// UnsafeBroadcastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcastServiceServer will
// result in compilation errors.
type UnsafeBroadcastServiceServer interface {
	mustEmbedUnimplementedBroadcastServiceServer()
}

func RegisterBroadcastServiceServer(s grpc.ServiceRegistrar, srv BroadcastServiceServer) {
	s.RegisterService(&BroadcastService_ServiceDesc, srv)
}

func _BroadcastService_BroadcastPlayerNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BroadcastRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServiceServer).BroadcastPlayerNotify(m, &broadcastServiceBroadcastPlayerNotifyServer{stream})
}

type BroadcastService_BroadcastPlayerNotifyServer interface {
	Send(*PlayerBroadcast) error
	grpc.ServerStream
}

type broadcastServiceBroadcastPlayerNotifyServer struct {
	grpc.ServerStream
}

func (x *broadcastServiceBroadcastPlayerNotifyServer) Send(m *PlayerBroadcast) error {
	return x.ServerStream.SendMsg(m)
}

// BroadcastService_ServiceDesc is the grpc.ServiceDesc for BroadcastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BroadcastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BroadcastService",
	HandlerType: (*BroadcastServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BroadcastPlayerNotify",
			Handler:       _BroadcastService_BroadcastPlayerNotify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/proto/broadcast.proto",
}
